[[main]]
  name = "Festival"
  identifier = "festival"
  url = "/"
  weight = 110
[[main]]
  name = "Activități"
  parent = "festival"
  url = "/activitati"
[[main]]
  name = "Turnee"
  parent = "festival"
  url = "/turnee"
[[main]]
  name = "Cazare"
  parent = "festival"
  url = "/cazare"
[[main]]
  name = "Premii"
  parent = "festival"
  url = "/premii"
[[main]]
  name = "Contact"
  parent = "festival"
  url = "/contact"
[[main]]
  name = "Regulamente"
  parent = "festival"
  url = "/regulamente"
[[main]]
  name = "Noutăți"
  url = "/noutati"
  weight = 120
[[main]]
  name = "Media"
  identifier = "media"
  weight = 125
[[main]]
  name = "Albume foto"
  parent = "media"
  url = "/albume-foto"
[[main]]
  name = "Video"
  parent = "media"
  url = "/video"
[[main]]
  name = "Live"
  identifier = "live"
  url = "/live"
  weight = 130
[[main]]
  name = "Live @chess24"
  post = "<i class=\"fas fa-external-link-alt\"></i>"
  parent = "live"
  url = "#"
[[main]]
  name = "Live @followchess"
  post = "<i class=\"fas fa-external-link-alt\"></i>"
  parent = "live"
  url = "#"
[[main]]
  name = "Înscriere"
  url = "/inscriere"
  weight = 140
[[main]]
  name = "Rezultate"
  identifier = "rezultate"
  url = "/rezultate"
  weight = 140
[[main]]
  name = "Piticot"
  parent = "rezultate"
  post = "<i class=\"fas fa-external-link-alt\"></i>"
  url = "https://chess-results.com/tnr443096.aspx"
[[main]]
  name = "Turneu A"
  parent = "rezultate"
  post = "<i class=\"fas fa-external-link-alt\"></i>"
  url = "https://chess-results.com/tnr443092.aspx"
[[main]]
  name = "Turneu B"
  parent = "rezultate"
  post = "<i class=\"fas fa-external-link-alt\"></i>"
  url = "https://chess-results.com/tnr443093.aspx"
[[main]]
  name = "Turneu C"
  parent = "rezultate"
  post = "<i class=\"fas fa-external-link-alt\"></i>"
  url = "https://chess-results.com/tnr443094.aspx"
[[main]]
  name = "Turneu D"
  parent = "rezultate"
  post = "<i class=\"fas fa-external-link-alt\"></i>"
  url = "https://chess-results.com/tnr443095.aspx"
