[[main]]
  name = "Program"
  url = "/program"
  weight = 110
[[main]]
  name = "Cazare"
  url = "/cazare"
  weight = 120
[[main]]
  name = "Live"
  identifier = "live"
  weight = 130
[[main]]
  name = "Live @chess24"
  post = "<i class=\"fas fa-external-link-alt\"></i>"
  parent = "live"
  url = "#"
[[main]]
  name = "Live @followchess"
  post = "<i class=\"fas fa-external-link-alt\"></i>"
  parent = "live"
  url = "#"
[[main]]
  name = "Înscriere"
  url = "/inscriere"
  weight = 140
[[main]]
  name = "Rezultate"
  identifier = "rezultate"
  weight = 140
[[main]]
  name = "Piticot"
  parent = "rezultate"
  post = "<i class=\"fas fa-external-link-alt\"></i>"
  url = "https://chess-results.com/tnr443096.aspx"
[[main]]
  name = "Turneu A"
  parent = "rezultate"
  post = "<i class=\"fas fa-external-link-alt\"></i>"
  url = "https://chess-results.com/tnr443092.aspx"
[[main]]
  name = "Turneu B"
  parent = "rezultate"
  post = "<i class=\"fas fa-external-link-alt\"></i>"
  url = "https://chess-results.com/tnr443093.aspx"
[[main]]
  name = "Turneu C"
  parent = "rezultate"
  post = "<i class=\"fas fa-external-link-alt\"></i>"
  url = "https://chess-results.com/tnr443094.aspx"
[[main]]
  name = "Turneu D"
  parent = "rezultate"
  post = "<i class=\"fas fa-external-link-alt\"></i>"
  url = "https://chess-results.com/tnr443095.aspx"
[[main]]
  name = "Contact"
  url = "/contact"
  weight = 160
