author = "Victor Ocnarescu"
sitename = "Fisca"
timeframe = "19 - 28 iunie 2020"
phone = "+40723574212"
description = "Festivalul Internațional de Șah Cap Aurora"
image = "/logo/fisca-wallpaper.jpg"
favicon = "/favicon/favicon.png"
analytics = "UA-29967399-1"
readMore = "Mai mult"
fontAwesome = true
[fonts]
  display = "'Libre Baskerville', serif"
  body = "'Open Sans', sans-serif"
  url = "https://fonts.googleapis.com/css?family=Libre+Baskerville|Open+Sans&display=swap"
[teaser]
  text = "Vrei să participi la unul dintre cele mai frumoase festivaluri de șah din România?"
  button = "Înscrie-te acum!"
  url = "/inscriere"
[[sponsors]]
  name = "Gerroma"
  image = "/sponsori/gerroma-logo.jpg"
  website = "https://www.gerroma.ro"
[[sponsors]]
  name = "Chipita"
  image = "/sponsori/chipita-logo.jpg"
  website = "https://www.chipita.com"
[[sponsors]]
  name = "Raiffeisen Bank"
  image = "/sponsori/raiffeisen-bank-logo.jpg"
  website = "https://www.raiffeisen.ro/"
[[sponsors]]
  name = "Oscar Downstream"
  image = "/sponsori/oscar-downstream-logo.jpg"
  website = "https://www.oscars.ro/"
[[icons]]
  icon = "fab fa-facebook-f"
  url = "https://www.facebook.com/FISCA.Romania/"
[[icons]]
  icon = "fab fa-instagram"
  url = "https://www.instagram.com/fisca_chess/"
[[icons]]
  icon = "fas fa-map-marker-alt"
  url = "https://goo.gl/maps/ZwHa9ezU1CFK8enB7"
