author = "Victor Ocnarescu"
fonts = "https://fonts.googleapis.com/css?family=Libre+Baskerville|Roboto&display=swap"
sitename = "Fisca"
timeframe = "19 - 28 iunie 2020"
description = "Festivalul International de Sah Cap Aurora"
image = "/logo/fisca-wallpaper.jpg"
favicon = "/favicon/favicon.png"
analytics = "UA-29967399-1"
fontAwesome = true
headingFont = "'Libre Baskerville', serif"
bodyFont = "'Roboto', sans-serif"
[teaser]
  text = "Vrei să participi la unul dintre cele mai frumoase festivaluri de șah din România?"
  button = "Înscrie-te acum!"
  url = "/inscriere"
[[sponsors]]
  name = "Gerroma"
[[sponsors]]
  name = "Chipita"
