backend:
  name: test-repo
media_folder: static/images
public_folder: /images
logo_url: /logo/fisca-logo-admin.png
collections:
  - name: pages
    label: Pages
    files:
      - name: partide-live
        label: Partide live
        file: content/partide-live/index.md
        fields:
          - label: Title
            name: title
            widget: string
          - label: Editions
            name: editions
            widget: list
            fields:
              - label: Year
                name: year
                widget: string
              - label: url
                name: url
                widget: string
          - label: Body
            name: body
            widget: markdown
  - name: settings
    label: Settings
    editor:
      preview: false
    files:
      - name: settings
        label: Update your website settings by clicking here
        file: config.toml
        fields:
          - widget: string
            name: title
            label: Title
            required: true
            hint: Site title
          - widget: object
            name: params
            label: Params
            required: true
            hint: Site parameters
            fields:
              - widget: string
                name: analytics
                label: Google Analytics Code
                required: false
  - name: menu
    label: Menus
    editor:
      preview: false
    files:
      - name: menu
        label: Update your website menu by clicking here
        file: config.toml
        fields:
          - widget: object
            name: menu
            label: Site Menus
            required: false
            hint: Menu items not related to a specific page
            fields:
              - widget: list
                name: main
                label: Main menu
                required: false
                hint: List of items for Main menu
                fields:
                  - widget: string
                    name: name
                    label: Menu text
                    required: true
                  - widget: string
                    name: url
                    label: Menu link
                    required: true
                  - widget: number
                    name: weight
                    label: Menu weight
                    required: true
                    hint: >-
                      A menu item is more important (placed more to the left)
                      if its weight is smaller
