backend:
  name: git-gateway
media_folder: static/images
public_folder: /images
logo_url: /logo/fisca-logo-admin.png
collections:
  - name: albume-foto
    label: Albume foto
    folder: content/albume-foto
    create: true
    slug: "{{slug}}"
    fields:
      - label: Title
        name: title
        widget: string
      - label: Date
        name: date
        widget: date
      - label: Image
        name: image
        widget: image
      - label: Link
        name: link
        widget: string
  - name: cazare
    label: Cazare
    folder: content/cazare
    create: true
    slug: "{{slug}}"
    fields:
      - label: Title
        name: title
        widget: string
      - label: Show in category list
        name: aside
        widget: boolean
        default: true
      - label: Image
        name: image
        widget: image
      - label: Prices
        name: prices
        widget: object
        fields:
          - label: Room Type
            name: type
            widget: string
          - label: Room prices
            name: prices
            widget: string
          - label: Meal details
            name: meal
            widget: string
      - label: Body
        name: body
        widget: markdown
  - name: settings
    label: Settings
    editor:
      preview: false
    files:
      - name: settings
        label: Update your website settings by clicking here
        file: config/_default/params.toml
        fields:
          - label: Sitename
            name: sitename
            widget: string
            required: true
          - label: Timeframe
            name: timeframe
            widget: string
            required: true
          - label: Phone number
            name: phone
            widget: string
            required: true
            hint: Phone number to display in the topbar
  - name: menu
    label: Menus
    editor:
      preview: false
    files:
      - name: menu
        label: Update your website menu by clicking here
        file: config/_default/menus.toml
        fields:
          - widget: object
            name: menu
            label: Site Menus
            required: false
            hint: Menu items not related to a specific page
            fields:
              - widget: list
                name: main
                label: Main menu
                required: false
                hint: List of items for Main menu
                fields:
                  - widget: string
                    name: name
                    label: Menu text
                    required: true
                  - widget: string
                    name: url
                    label: Menu link
                    required: true
                  - widget: number
                    name: weight
                    label: Menu weight
                    required: true
                    hint: >-
                      A menu item is more important (placed more to the left)
                      if its weight is smaller
