backend:
  name: git-gateway
media_folder: static/images
public_folder: /images
logo_url: /logo/fisca-logo-admin.png
collections:
  - name: albume-foto
    label: Albume foto
    folder: content/albume-foto
    create: true
    slug: "{{slug}}"
    editor:
      preview: false
    fields:
      - label: Title
        name: title
        widget: string
      - label: Date
        name: date
        widget: date
      - label: Image
        name: image
        widget: image
      - label: Link
        name: link
        widget: string
  - name: noutati
    label: Noutăți
    folder: content/noutati
    create: true
    slug: "{{slug}}"
    editor:
      preview: false
    fields:
      - label: Title
        name: title
        widget: string
      - label: Show in category list
        name: aside
        widget: boolean
        default: true
      - label: Date
        name: date
        widget: date
      - label: Author
        name: author
        widget: string
      - label: Body
        name: body
        widget: markdown
  - name: regulamente
    label: Regulamente
    folder: content/regulamente
    create: true
    slug: "{{slug}}"
    editor:
      preview: false
    fields:
      - label: Title
        name: title
        widget: string
      - label: Show in category list
        name: aside
        widget: boolean
        default: true
      - label: Date
        name: date
        widget: date
      - label: Author
        name: author
        widget: string
      - label: Body
        name: body
        widget: markdown
  - name: cazare
    label: Cazare
    folder: content/cazare
    create: true
    slug: "{{slug}}"
    editor:
      preview: false
    fields:
      - label: Title
        name: title
        widget: string
      - label: Show in category list
        name: aside
        widget: boolean
        default: true
      - label: Image
        name: image
        widget: image
      - label: Prices
        name: prices
        widget: object
        fields:
          - label: Room Type
            name: type
            widget: string
          - label: Room prices
            name: prices
            widget: string
          - label: Meal details
            name: meal
            widget: string
      - label: Body
        name: body
        widget: markdown
  - name: settings
    label: Settings
    editor:
      preview: false
    files:
      - name: settings
        label: Update your website settings by clicking here
        file: config/_default/params.toml
        fields:
          - label: Timeframe
            name: timeframe
            widget: string
            required: true
          - label: Phone number
            name: phone
            widget: string
            required: true
            hint: Phone number to display in the topbar
          - label: Sponsori
            name: sponsors
            widget: list
            fields:
              - label: Sponsor name
                name: name
                widget: string
              - label: Logo
                name: image
                widget: image
              - label: Website
                name: website
                widget: string
          - label: Topbar Icons
            name: icons
            widget: list
            fields:
              - label: FontAwesome icon
                name: icon
                widget: string
              - label: URL
                name: url
                widget: string
  - name: menu
    label: Menus
    editor:
      preview: false
    files:
      - name: menu
        label: Update your website menu by clicking here
        file: config/_default/menus.toml
        fields:
          - label: Site Menus
            name: main
            widget: list
            fields:
              - label: Menu text
                name: name
                widget: string
                required: true
              - label: Menu link
                name: url
                widget: string
                required: true
              - label: Menu weight
                name: weight
                widget: number
                hint: Optional. The menu item is more important (placed more to the left) if its weight is smaller
              - label: Menu identifier
                name: identifier
                widget: string
                hint: Only for parent menu items
              - label: Menu parent
                name: parent
                widget: string
                hint: Only for submenu items
